# Generated by Django 5.0 on 2023-12-12 17:01

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name = "Film",
            fields = [
                ("id", models.BigAutoField(auto_created = True, primary_key = True, serialize = False, verbose_name = "ID")),
                ("title", models.CharField(max_length = 500, verbose_name = "title")),
                ("vote_average", models.FloatField(verbose_name = "vote_average")),
                ("vote_count", models.IntegerField(verbose_name = "vote_count")),
                ("release_date", models.DateField(verbose_name = "release_date")),
                ("revenue", models.IntegerField(verbose_name = "revenue")),
                ("runtime", models.IntegerField(verbose_name = "runtime")),
                ("adult", models.BooleanField(verbose_name = "adult")),
                ("budget", models.IntegerField(verbose_name = "budget")),
                ("popularity", models.FloatField(verbose_name = "popularity")),
                ("poster_path", models.CharField(max_length = 1500, verbose_name = "poster_path")),
                ("genres", models.CharField(max_length = 1500, verbose_name = "genres")),
            ],
        ),
    ]